var settings = {
  "CasterCD": true,
  "CooldownWinLevel": 2,
  "CooldownAdd": 0,
  "command_win_level": "!winlevel",
  "command_refresh_overlay": "!refreshlevels",
  "RespLevelAddError": "Ha ocurrido un error al intentar agregar el nivel a la cola, avisa a un mod",
  "UseCD": true,
  "command_skip_level": "!skiplevel",
  "OnQueueLimitReached": "@{0} La cola está llena ({1} niveles máximo). Espera a que se libere un hueco para añadir tu nivel",
  "Cooldown": 0,
  "CooldownNextLevel": 3,
  "RespWrongLevelCodeFormat": "Código de nivel incorrecto, el formato debe coincidir con XXX-YYY-ZZZ, caracteres alfanuméricos sin símbolos ni las letras I, O",
  "RespPermissionAdvanced": "$user -> Sólo $permissionadvanced ($permissioninfoadvanced) o superior pueden usar este comando",
  "CooldownCurrentLevel": 3,
  "CooldownDeleteLevel": 2,
  "UserCooldownList": 10,
  "is_queue_limited": false,
  "command_current_level": "!level",
  "RespOverlayUpdated": "Here we go! Overlay de niveles actualizado",
  "RespLevelFinishedSkip": "Nivel skipeado.",
  "RespErrorReadingQueue": "Error al intentar leer la lista de niveles, avisa a un mod",
  "CooldownRefreshOverlay": 2,
  "OnDuplicatedLevel": "@{0} El nivel {1} ya está en la cola. Los niveles duplicados se omiten",
  "PermissionAdvanced": "Moderator",
  "RespErrorLevelAdd": "Error del sistema al añadir el nivel a la cola, avisa a un mod",
  "is_user_limited": false,
  "command_add": "!add",
  "command_delete_level": "!deletelevel",
  "RespNextLevel": "El siguiente nivel es {0}",
  "command_info": "!smm2lqs",
  "UserCooldownNextLevel": 3,
  "Usage": "Stream Chat",
  "command_queue_close": "!queueclose",
  "max_levels_by_user": 3,
  "OnMaxLevelsByUserReached": "@{0} Has alcanzado el máximo de niveles por persona ({1}), espera a que se complete alguno de tus niveles para añadir otro",
  "RespUserLevelPositionsNoLevels": "@{0} no tienes niveles en cola",
  "UserCooldownDeleteLevel": 2,
  "QueueOpen": true,
  "UserCooldownRefreshOverlay": 2,
  "RespLevelFinishedDelete": "Nivel eliminado.",
  "UserCooldownWinLevel": 2,
  "RespCurrentLevelRequested": "@{0} El nivel en juego es {1}",
  "CooldownSkipLevel": 2,
  "RespNextLevelRequested": "@{0} El siguiente nivel en cola es {1}",
  "RespQueueClosed": "Cola de niveles cerrada! Espera a que un mod la vuelva a abrir para añadir tus niveles",
  "OnCooldown": "@{0} el comando {1} aún está en cooldown global. Espera {2} segundos",
  "command_position": "!position",
  "UserCooldownSkipLevel": 2,
  "command_next_level": "!nextlevel",
  "OnlyLive": false,
  "RespErrorOverlayUpdate": "Error actualizando el overlay de niveles. Dale un toque a alguien del staff",
  "UserCooldownAdd": 3,
  "CooldownPosition": 0,
  "RespNoMoreLevels": "No hay más niveles en cola, añade el tuyo con {0}",
  "OnUserCooldown": "@{0} aún faltan {2} segundos para que puedas usar el comando {1}",
  "PermissionInfoAdvanced": "",
  "RespLevelAdded": "@{0} ha añadido el nivel {1} a la cola en la posición [{2}]",
  "command_queue_open": "!queueopen",
  "UserCooldownCurrentLevel": 3,
  "RespQueueOpened": "Cola de niveles abierta! Usa {0} <código> para añadir niveles a la cola",
  "command_list": "!list",
  "PermissionInfoBase": "",
  "CooldownList": 10,
  "UserCooldownPosition": 10,
  "RespInfo": "{0} <código> (En formato XXX-YYY-ZZZ, caracteres alfanuméricos excluyendo I, O) para añadir un nivel a la lista. {1}, {2}, {3} o {4} para info",
  "RespUserLevelPositions": "@{0} tienes niveles en las posiciones {1}",
  "UserCooldown": 10,
  "RespLevelFinishedWin": "¡Nivel superado!",
  "RespNoLevelsOnQueue": "No hay niveles en la cola. Añade el tuyo usando {0}",
  "RespPermissionBase": "$user -> Sólo $permissionbase ($permissioninfobase) o superior pueden usar este comando",
  "PermissionBase": "Everyone",
  "omit_duplicated_levels": true,
  "queue_length": 25,
  "RespErrorModifyingQueue": "Error al intentar actualizar la lista de niveles, avisa a un mod",
  "CooldownInfo": 0,
  "UserCooldownInfo": 3
};