var settings = {
  "OnlyLive": false,
  "command_add": "!add",
  "command_list": "!list",
  "command_position": "!position",
  "command_current_level": "!level",
  "command_next_level": "!nextlevel",
  "command_win_level": "!winlevel",
  "command_skip_level": "!skiplevel",
  "command_refresh_overlay": "!refreshlevels",
  "PermissionBase": "Everyone",
  "PermissionInfoBase": "",
  "PermissionAdvanced": "Moderator",
  "PermissionInfoAdvanced": "",
  "Usage": "Stream Chat",
  "is_queue_limited": false,
  "queue_length": 25,
  "is_user_limited": false,
  "max_levels_by_user": 3,
  "UseCD": false,
  "Cooldown": 0,
  "OnCooldown": "{0} the command is still on cooldown for {1} seconds!",
  "UserCooldown": 10,
  "OnUserCooldown": "{0} the command is still on user cooldown for {1} seconds!",
  "CasterCD": true,
  "RespInfo": "!add <código> para añadir un nivel a la lista. !level, !nextlevel o !list para info",
  "RespPermissionBase": "$user -> Sólo $permissionbase ($permissioninfobase) o superior pueden usar este comando",
  "RespPermissionAdvanced": "$user -> Sólo $permissionadvanced ($permissioninfoadvanced) o superior pueden usar este comando",
  "OnQueueLimitReached": "@{0} La cola está llena ({1} niveles máximo). Espera a que se libere un hueco para añadir tu nivel",
  "OnMaxLevelsByUserReached": "@{0} Has alcanzado el máximo de niveles por persona ({1}), espera a que se complete alguno de tus niveles para añadir otro",
  "RespLevelAdded": "@{0} ha añadido el nivel {1} a la cola en la posición [{2}]",
  "RespLevelAddError": "Ha ocurrido un error al intentar agregar el nivel a la cola, avisa a un mod",
  "RespWrongLevelCodeFormat": "Código de nivel incorrecto, el formato debe coincidir con XXX-YYY-ZZZ, caracteres alfanuméricos sin símbolos ni las letras I, O",
  "RespNoLevelsOnQueue": "No hay niveles en la cola. Añade el tuyo usando {0}",
  "RespErrorReadingQueue": "Error al intentar leer la lista de niveles, avisa a un mod",
  "RespUserLevelPositions": "@{0} tienes niveles en las posiciones {1}",
  "RespUserLevelPositionsNoLevels": "@{0} no tienes niveles en cola",
  "RespLevelFinishedWin": "¡Nivel superado!",
  "RespLevelFinishedSkip": "Nivel skipeado.",
  "RespNextLevel": "El siguiente nivel es {0}",
  "RespNoMoreLevels": "No hay más niveles en cola, añade el tuyo con {0}",
  "RespErrorLevelAdd": "System error adding level to queue, call a mod",
  "RespErrorModifyingQueue": "Error updating queue file, call a mod",
  "RespOverlayUpdated": "Here we go! Overlay de niveles actualizado",
  "RespErrorOverlayUpdate": "Error actualizando el overlay de niveles. Dale un toque a alguien del staff"
};